// SPDX-License-Identifier: MIT
pragma solidity ^0.8.26;

/// Poseidon hashers generated by circomlibjs (contracts/poseidon/*.bin)
interface IPoseidonT3 {
    function poseidon(uint256[2] calldata input) external pure returns (uint256);
}

interface IPoseidonT4 {
    function poseidon(uint256[3] calldata input) external pure returns (uint256);
}

interface IVerifier {
    function verifyProof(
        uint256[2] calldata a,
        uint256[2][2] calldata b,
        uint256[2] calldata c,
        uint256[7] calldata pubSignals
    ) external view returns (bool);
}

interface IShieldedPool {
    function depositFor(uint256 pubKey, uint256 blinding) external payable returns (uint256 leafIndex);
}

enum PayoutMode {
    Creator,
    Wallet,
    Holders,
    Donate
}

interface IFeeRouter {
    function collect(address coin) external payable;
    function registerCoin(
        address coin,
        address creator,
        PayoutMode mode,
        address payoutWallet,
        uint256 ringId,
        bool isRootstock
    ) external;
    function treasury() external view returns (address);
    function launchpad() external view returns (address);
    function roots() external view returns (address);
    function keeper() external view returns (address);
}

interface IRoots {
    function deposit(address coin) external payable;
}

interface IHolderRewards {
    function fund(address coin) external payable;
}

interface IDonationRotator {
    function fund(address coin) external payable;
    function bindCoin(address coin, uint256 ringId) external;
    function ringExists(uint256 ringId) external view returns (bool);
}

interface IGroveCoin {
    function setPair(address pair) external;
    function setExempt(address account, bool exempt) external;
    function burnFrom(address account, uint256 amount) external;
    function burn(uint256 amount) external;
    function totalSupply() external view returns (uint256);
    function isRootstock() external view returns (bool);
}

interface ILaunchpad {
    function buy(address coin, uint256 minTokensOut) external payable returns (uint256 tokensOut);
    function isGraduated(address coin) external view returns (bool);
    function pairOf(address coin) external view returns (address);
}
