// GENERATED by keeper/scripts/sync-abis.mjs from contracts/out. Do not edit by hand; rerun `npm run sync:abis`.
// Privacy stage 2 (privacy/PRIVACY-SPEC.md section 4). Kept out of abis.ts so the stage-1 ABIs stay hand-written.

export const grovePoolAbi = [
  {
    "type": "constructor",
    "inputs": [
      {
        "name": "transferVerifier_",
        "type": "address"
      },
      {
        "name": "poseidonT3_",
        "type": "address"
      },
      {
        "name": "poseidonT4_",
        "type": "address"
      },
      {
        "name": "launchpad_",
        "type": "address"
      },
      {
        "name": "holderRewards_",
        "type": "address"
      },
      {
        "name": "v1_",
        "type": "address"
      },
      {
        "name": "owner_",
        "type": "address"
      }
    ],
    "stateMutability": "nonpayable"
  },
  {
    "type": "receive",
    "stateMutability": "payable"
  },
  {
    "type": "function",
    "name": "CHECKPOINT_PERIOD",
    "inputs": [],
    "outputs": [
      {
        "name": "",
        "type": "uint32"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "FIELD_SIZE",
    "inputs": [],
    "outputs": [
      {
        "name": "",
        "type": "uint256"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "ZERO_VALUE",
    "inputs": [],
    "outputs": [
      {
        "name": "",
        "type": "uint256"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "accRpt",
    "inputs": [
      {
        "name": "coin",
        "type": "address"
      }
    ],
    "outputs": [
      {
        "name": "",
        "type": "uint256"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "acceptOwnership",
    "inputs": [],
    "outputs": [],
    "stateMutability": "nonpayable"
  },
  {
    "type": "function",
    "name": "addTokenLot",
    "inputs": [
      {
        "name": "units",
        "type": "uint256"
      }
    ],
    "outputs": [],
    "stateMutability": "nonpayable"
  },
  {
    "type": "function",
    "name": "addUnshieldDenomination",
    "inputs": [
      {
        "name": "wei_",
        "type": "uint256"
      }
    ],
    "outputs": [],
    "stateMutability": "nonpayable"
  },
  {
    "type": "function",
    "name": "checkpoint",
    "inputs": [],
    "outputs": [],
    "stateMutability": "nonpayable"
  },
  {
    "type": "function",
    "name": "chunksLeft",
    "inputs": [],
    "outputs": [
      {
        "name": "",
        "type": "uint256"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "claimable",
    "inputs": [
      {
        "name": "handle",
        "type": "uint256"
      }
    ],
    "outputs": [
      {
        "name": "",
        "type": "uint256"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "credit",
    "inputs": [
      {
        "name": "handle",
        "type": "uint256"
      }
    ],
    "outputs": [],
    "stateMutability": "payable"
  },
  {
    "type": "function",
    "name": "darkCurve",
    "inputs": [],
    "outputs": [
      {
        "name": "",
        "type": "address"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "filledSubtrees",
    "inputs": [
      {
        "name": "",
        "type": "uint256"
      }
    ],
    "outputs": [
      {
        "name": "",
        "type": "uint256"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "getLastRoot",
    "inputs": [],
    "outputs": [
      {
        "name": "",
        "type": "uint256"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "hashExtData",
    "inputs": [
      {
        "name": "e",
        "type": "tuple",
        "components": [
          {
            "name": "recipient",
            "type": "address"
          },
          {
            "name": "extAmountBnb",
            "type": "int256"
          },
          {
            "name": "extAmountCoin",
            "type": "int256"
          },
          {
            "name": "relayer",
            "type": "address"
          },
          {
            "name": "fee",
            "type": "uint256"
          },
          {
            "name": "payload",
            "type": "bytes"
          },
          {
            "name": "encryptedOutputs",
            "type": "bytes[3]"
          }
        ]
      }
    ],
    "outputs": [
      {
        "name": "",
        "type": "bytes32"
      }
    ],
    "stateMutability": "pure"
  },
  {
    "type": "function",
    "name": "hashLeftRight",
    "inputs": [
      {
        "name": "left",
        "type": "uint256"
      },
      {
        "name": "right",
        "type": "uint256"
      }
    ],
    "outputs": [
      {
        "name": "",
        "type": "uint256"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "hasher",
    "inputs": [],
    "outputs": [
      {
        "name": "",
        "type": "address"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "holderRewards",
    "inputs": [],
    "outputs": [
      {
        "name": "",
        "type": "address"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "insertChunk",
    "inputs": [
      {
        "name": "leaves",
        "type": "uint256[4]"
      },
      {
        "name": "encryptedOutputs",
        "type": "bytes[]"
      }
    ],
    "outputs": [
      {
        "name": "",
        "type": "uint32"
      }
    ],
    "stateMutability": "nonpayable"
  },
  {
    "type": "function",
    "name": "isCoin",
    "inputs": [
      {
        "name": "coin",
        "type": "address"
      }
    ],
    "outputs": [
      {
        "name": "",
        "type": "bool"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "isKnownRoot",
    "inputs": [
      {
        "name": "root",
        "type": "uint256"
      }
    ],
    "outputs": [
      {
        "name": "",
        "type": "bool"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "isSpent",
    "inputs": [
      {
        "name": "nullifier",
        "type": "uint256"
      }
    ],
    "outputs": [
      {
        "name": "",
        "type": "bool"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "knownAccRpt",
    "inputs": [
      {
        "name": "coin",
        "type": "address"
      },
      {
        "name": "value",
        "type": "uint256"
      }
    ],
    "outputs": [
      {
        "name": "",
        "type": "bool"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "lastCheckpointPeriod",
    "inputs": [],
    "outputs": [
      {
        "name": "",
        "type": "uint64"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "lastRoot",
    "inputs": [],
    "outputs": [
      {
        "name": "",
        "type": "uint256"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "launchpad",
    "inputs": [],
    "outputs": [
      {
        "name": "",
        "type": "address"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "levels",
    "inputs": [],
    "outputs": [
      {
        "name": "",
        "type": "uint32"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "markSpent",
    "inputs": [
      {
        "name": "nullifier",
        "type": "uint256"
      }
    ],
    "outputs": [],
    "stateMutability": "nonpayable"
  },
  {
    "type": "function",
    "name": "maxShieldPerTx",
    "inputs": [],
    "outputs": [
      {
        "name": "",
        "type": "uint256"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "migrateFromV1",
    "inputs": [
      {
        "name": "vp",
        "type": "tuple",
        "components": [
          {
            "name": "a",
            "type": "uint256[2]"
          },
          {
            "name": "b",
            "type": "uint256[2][2]"
          },
          {
            "name": "c",
            "type": "uint256[2]"
          },
          {
            "name": "root",
            "type": "uint256"
          },
          {
            "name": "publicAmount",
            "type": "uint256"
          },
          {
            "name": "extDataHash",
            "type": "bytes32"
          },
          {
            "name": "inputNullifiers",
            "type": "uint256[2]"
          },
          {
            "name": "outputCommitments",
            "type": "uint256[2]"
          }
        ]
      },
      {
        "name": "ve",
        "type": "tuple",
        "components": [
          {
            "name": "recipient",
            "type": "address"
          },
          {
            "name": "extAmount",
            "type": "int256"
          },
          {
            "name": "relayer",
            "type": "address"
          },
          {
            "name": "fee",
            "type": "uint256"
          },
          {
            "name": "encryptedOutput1",
            "type": "bytes"
          },
          {
            "name": "encryptedOutput2",
            "type": "bytes"
          }
        ]
      },
      {
        "name": "handle",
        "type": "uint256"
      }
    ],
    "outputs": [],
    "stateMutability": "nonpayable"
  },
  {
    "type": "function",
    "name": "moveOut",
    "inputs": [
      {
        "name": "asset",
        "type": "address"
      },
      {
        "name": "amount",
        "type": "uint256"
      },
      {
        "name": "to",
        "type": "address"
      }
    ],
    "outputs": [],
    "stateMutability": "nonpayable"
  },
  {
    "type": "function",
    "name": "nextIndex",
    "inputs": [],
    "outputs": [
      {
        "name": "",
        "type": "uint32"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "nullifierHashes",
    "inputs": [
      {
        "name": "",
        "type": "uint256"
      }
    ],
    "outputs": [
      {
        "name": "",
        "type": "bool"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "owner",
    "inputs": [],
    "outputs": [
      {
        "name": "",
        "type": "address"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "pendingOwner",
    "inputs": [],
    "outputs": [
      {
        "name": "",
        "type": "address"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "planter",
    "inputs": [],
    "outputs": [
      {
        "name": "",
        "type": "address"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "pullRewards",
    "inputs": [
      {
        "name": "coin",
        "type": "address"
      },
      {
        "name": "runId",
        "type": "uint256"
      },
      {
        "name": "amount",
        "type": "uint256"
      },
      {
        "name": "proof",
        "type": "bytes32[]"
      }
    ],
    "outputs": [],
    "stateMutability": "nonpayable"
  },
  {
    "type": "function",
    "name": "renounceOwnership",
    "inputs": [],
    "outputs": [],
    "stateMutability": "nonpayable"
  },
  {
    "type": "function",
    "name": "rootIndexAfter",
    "inputs": [
      {
        "name": "root",
        "type": "uint256"
      }
    ],
    "outputs": [
      {
        "name": "indexAfter",
        "type": "uint32"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "router",
    "inputs": [],
    "outputs": [
      {
        "name": "",
        "type": "address"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "setMaxShield",
    "inputs": [
      {
        "name": "v",
        "type": "uint256"
      }
    ],
    "outputs": [],
    "stateMutability": "nonpayable"
  },
  {
    "type": "function",
    "name": "setModules",
    "inputs": [
      {
        "name": "darkCurve_",
        "type": "address"
      },
      {
        "name": "planter_",
        "type": "address"
      }
    ],
    "outputs": [],
    "stateMutability": "nonpayable"
  },
  {
    "type": "function",
    "name": "t4",
    "inputs": [],
    "outputs": [
      {
        "name": "",
        "type": "address"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "toField",
    "inputs": [
      {
        "name": "x",
        "type": "int256"
      }
    ],
    "outputs": [
      {
        "name": "",
        "type": "uint256"
      }
    ],
    "stateMutability": "pure"
  },
  {
    "type": "function",
    "name": "tokenLot",
    "inputs": [
      {
        "name": "amount",
        "type": "uint256"
      }
    ],
    "outputs": [
      {
        "name": "",
        "type": "bool"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "transact",
    "inputs": [
      {
        "name": "p",
        "type": "tuple",
        "components": [
          {
            "name": "a",
            "type": "uint256[2]"
          },
          {
            "name": "b",
            "type": "uint256[2][2]"
          },
          {
            "name": "c",
            "type": "uint256[2]"
          }
        ]
      },
      {
        "name": "s",
        "type": "tuple",
        "components": [
          {
            "name": "root",
            "type": "uint256"
          },
          {
            "name": "publicAmount",
            "type": "uint256"
          },
          {
            "name": "coin",
            "type": "address"
          },
          {
            "name": "publicAmountCoin",
            "type": "uint256"
          },
          {
            "name": "accRpt",
            "type": "uint256"
          },
          {
            "name": "handle",
            "type": "uint256"
          },
          {
            "name": "claimAmount",
            "type": "uint256"
          },
          {
            "name": "extDataHash",
            "type": "bytes32"
          },
          {
            "name": "inputNullifiers",
            "type": "uint256[2]"
          },
          {
            "name": "outputCommitments",
            "type": "uint256[3]"
          }
        ]
      },
      {
        "name": "e",
        "type": "tuple",
        "components": [
          {
            "name": "recipient",
            "type": "address"
          },
          {
            "name": "extAmountBnb",
            "type": "int256"
          },
          {
            "name": "extAmountCoin",
            "type": "int256"
          },
          {
            "name": "relayer",
            "type": "address"
          },
          {
            "name": "fee",
            "type": "uint256"
          },
          {
            "name": "payload",
            "type": "bytes"
          },
          {
            "name": "encryptedOutputs",
            "type": "bytes[3]"
          }
        ]
      }
    ],
    "outputs": [],
    "stateMutability": "payable"
  },
  {
    "type": "function",
    "name": "transferOwnership",
    "inputs": [
      {
        "name": "newOwner",
        "type": "address"
      }
    ],
    "outputs": [],
    "stateMutability": "nonpayable"
  },
  {
    "type": "function",
    "name": "transferVerifier",
    "inputs": [],
    "outputs": [
      {
        "name": "",
        "type": "address"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "unshieldDenom",
    "inputs": [
      {
        "name": "amount",
        "type": "uint256"
      }
    ],
    "outputs": [
      {
        "name": "",
        "type": "bool"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "v1",
    "inputs": [],
    "outputs": [
      {
        "name": "",
        "type": "address"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "verifyTransfer",
    "inputs": [
      {
        "name": "p",
        "type": "tuple",
        "components": [
          {
            "name": "a",
            "type": "uint256[2]"
          },
          {
            "name": "b",
            "type": "uint256[2][2]"
          },
          {
            "name": "c",
            "type": "uint256[2]"
          }
        ]
      },
      {
        "name": "s",
        "type": "tuple",
        "components": [
          {
            "name": "root",
            "type": "uint256"
          },
          {
            "name": "publicAmount",
            "type": "uint256"
          },
          {
            "name": "coin",
            "type": "address"
          },
          {
            "name": "publicAmountCoin",
            "type": "uint256"
          },
          {
            "name": "accRpt",
            "type": "uint256"
          },
          {
            "name": "handle",
            "type": "uint256"
          },
          {
            "name": "claimAmount",
            "type": "uint256"
          },
          {
            "name": "extDataHash",
            "type": "bytes32"
          },
          {
            "name": "inputNullifiers",
            "type": "uint256[2]"
          },
          {
            "name": "outputCommitments",
            "type": "uint256[3]"
          }
        ]
      }
    ],
    "outputs": [
      {
        "name": "",
        "type": "bool"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "zeros",
    "inputs": [
      {
        "name": "",
        "type": "uint256"
      }
    ],
    "outputs": [
      {
        "name": "",
        "type": "uint256"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "event",
    "name": "Checkpoint",
    "inputs": [
      {
        "name": "root",
        "type": "uint256",
        "indexed": false
      },
      {
        "name": "indexAfter",
        "type": "uint32",
        "indexed": false
      },
      {
        "name": "period",
        "type": "uint64",
        "indexed": false
      }
    ],
    "anonymous": false
  },
  {
    "type": "event",
    "name": "CommitmentDropped",
    "inputs": [
      {
        "name": "commitment",
        "type": "uint256",
        "indexed": true
      }
    ],
    "anonymous": false
  },
  {
    "type": "event",
    "name": "Credited",
    "inputs": [
      {
        "name": "handle",
        "type": "uint256",
        "indexed": true
      },
      {
        "name": "amount",
        "type": "uint256",
        "indexed": false
      }
    ],
    "anonymous": false
  },
  {
    "type": "event",
    "name": "DenominationAdded",
    "inputs": [
      {
        "name": "token",
        "type": "bool",
        "indexed": false
      },
      {
        "name": "amount",
        "type": "uint256",
        "indexed": false
      }
    ],
    "anonymous": false
  },
  {
    "type": "event",
    "name": "HandleClaimed",
    "inputs": [
      {
        "name": "handle",
        "type": "uint256",
        "indexed": true
      },
      {
        "name": "claimAmount",
        "type": "uint256",
        "indexed": false
      }
    ],
    "anonymous": false
  },
  {
    "type": "event",
    "name": "MaxShieldSet",
    "inputs": [
      {
        "name": "maxShieldPerTx",
        "type": "uint256",
        "indexed": false
      }
    ],
    "anonymous": false
  },
  {
    "type": "event",
    "name": "MigratedFromV1",
    "inputs": [
      {
        "name": "handle",
        "type": "uint256",
        "indexed": true
      },
      {
        "name": "amount",
        "type": "uint256",
        "indexed": false
      }
    ],
    "anonymous": false
  },
  {
    "type": "event",
    "name": "ModulesSet",
    "inputs": [
      {
        "name": "darkCurve",
        "type": "address",
        "indexed": false
      },
      {
        "name": "planter",
        "type": "address",
        "indexed": false
      }
    ],
    "anonymous": false
  },
  {
    "type": "event",
    "name": "NewCommitment",
    "inputs": [
      {
        "name": "commitment",
        "type": "uint256",
        "indexed": true
      },
      {
        "name": "index",
        "type": "uint32",
        "indexed": false
      },
      {
        "name": "encryptedOutput",
        "type": "bytes",
        "indexed": false
      }
    ],
    "anonymous": false
  },
  {
    "type": "event",
    "name": "NewNullifier",
    "inputs": [
      {
        "name": "nullifier",
        "type": "uint256",
        "indexed": false
      }
    ],
    "anonymous": false
  },
  {
    "type": "event",
    "name": "OwnershipTransferStarted",
    "inputs": [
      {
        "name": "previousOwner",
        "type": "address",
        "indexed": true
      },
      {
        "name": "newOwner",
        "type": "address",
        "indexed": true
      }
    ],
    "anonymous": false
  },
  {
    "type": "event",
    "name": "OwnershipTransferred",
    "inputs": [
      {
        "name": "previousOwner",
        "type": "address",
        "indexed": true
      },
      {
        "name": "newOwner",
        "type": "address",
        "indexed": true
      }
    ],
    "anonymous": false
  },
  {
    "type": "event",
    "name": "RewardsPulled",
    "inputs": [
      {
        "name": "coin",
        "type": "address",
        "indexed": true
      },
      {
        "name": "runId",
        "type": "uint256",
        "indexed": false
      },
      {
        "name": "amount",
        "type": "uint256",
        "indexed": false
      },
      {
        "name": "accRpt",
        "type": "uint256",
        "indexed": false
      }
    ],
    "anonymous": false
  },
  {
    "type": "event",
    "name": "Transact",
    "inputs": [
      {
        "name": "extAmountBnb",
        "type": "int256",
        "indexed": false
      },
      {
        "name": "coin",
        "type": "address",
        "indexed": false
      },
      {
        "name": "extAmountCoin",
        "type": "int256",
        "indexed": false
      },
      {
        "name": "recipient",
        "type": "address",
        "indexed": false
      },
      {
        "name": "relayer",
        "type": "address",
        "indexed": false
      },
      {
        "name": "fee",
        "type": "uint256",
        "indexed": false
      }
    ],
    "anonymous": false
  },
  {
    "type": "error",
    "name": "AlreadySpent",
    "inputs": []
  },
  {
    "type": "error",
    "name": "BadClaimAmount",
    "inputs": []
  },
  {
    "type": "error",
    "name": "BadExtDataHash",
    "inputs": []
  },
  {
    "type": "error",
    "name": "BadPayload",
    "inputs": []
  },
  {
    "type": "error",
    "name": "BadPlantValue",
    "inputs": []
  },
  {
    "type": "error",
    "name": "BadPublicAmount",
    "inputs": []
  },
  {
    "type": "error",
    "name": "BadValue",
    "inputs": []
  },
  {
    "type": "error",
    "name": "InvalidProof",
    "inputs": []
  },
  {
    "type": "error",
    "name": "MigrationNotBound",
    "inputs": []
  },
  {
    "type": "error",
    "name": "ModulesAlreadySet",
    "inputs": []
  },
  {
    "type": "error",
    "name": "NotCoin",
    "inputs": []
  },
  {
    "type": "error",
    "name": "NotDenomination",
    "inputs": []
  },
  {
    "type": "error",
    "name": "NotInField",
    "inputs": []
  },
  {
    "type": "error",
    "name": "NotModule",
    "inputs": []
  },
  {
    "type": "error",
    "name": "NotPoolSender",
    "inputs": []
  },
  {
    "type": "error",
    "name": "OverLimit",
    "inputs": []
  },
  {
    "type": "error",
    "name": "OwnableInvalidOwner",
    "inputs": [
      {
        "name": "owner",
        "type": "address"
      }
    ]
  },
  {
    "type": "error",
    "name": "OwnableUnauthorizedAccount",
    "inputs": [
      {
        "name": "account",
        "type": "address"
      }
    ]
  },
  {
    "type": "error",
    "name": "ReentrancyGuardReentrantCall",
    "inputs": []
  },
  {
    "type": "error",
    "name": "SafeERC20FailedOperation",
    "inputs": [
      {
        "name": "token",
        "type": "address"
      }
    ]
  },
  {
    "type": "error",
    "name": "TransferFailed",
    "inputs": []
  },
  {
    "type": "error",
    "name": "TreeFull",
    "inputs": []
  },
  {
    "type": "error",
    "name": "UnknownAccRpt",
    "inputs": []
  },
  {
    "type": "error",
    "name": "UnknownRoot",
    "inputs": []
  }
] as const;

export const darkCurveAbi = [
  {
    "type": "constructor",
    "inputs": [
      {
        "name": "pool_",
        "type": "address"
      },
      {
        "name": "roots_",
        "type": "address"
      },
      {
        "name": "treasury_",
        "type": "address"
      },
      {
        "name": "intentVerifier_",
        "type": "address"
      },
      {
        "name": "claimVerifier_",
        "type": "address"
      },
      {
        "name": "openVerifier_",
        "type": "address"
      },
      {
        "name": "coordinatorPk",
        "type": "uint256[2]"
      },
      {
        "name": "owner_",
        "type": "address"
      }
    ],
    "stateMutability": "nonpayable"
  },
  {
    "type": "receive",
    "stateMutability": "payable"
  },
  {
    "type": "function",
    "name": "acceptOwnership",
    "inputs": [],
    "outputs": [],
    "stateMutability": "nonpayable"
  },
  {
    "type": "function",
    "name": "activeCoordinatorKey",
    "inputs": [],
    "outputs": [
      {
        "name": "pk",
        "type": "uint256[2]"
      },
      {
        "name": "gen",
        "type": "uint32"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "claim",
    "inputs": [
      {
        "name": "p",
        "type": "tuple",
        "components": [
          {
            "name": "a",
            "type": "uint256[2]"
          },
          {
            "name": "b",
            "type": "uint256[2][2]"
          },
          {
            "name": "c",
            "type": "uint256[2]"
          }
        ]
      },
      {
        "name": "s",
        "type": "tuple",
        "components": [
          {
            "name": "root",
            "type": "uint256"
          },
          {
            "name": "nullifier",
            "type": "uint256"
          },
          {
            "name": "outputCommitments",
            "type": "uint256[2]"
          },
          {
            "name": "extDataHash",
            "type": "bytes32"
          }
        ]
      },
      {
        "name": "e",
        "type": "tuple",
        "components": [
          {
            "name": "relayer",
            "type": "address"
          },
          {
            "name": "encryptedOutputs",
            "type": "bytes[2]"
          }
        ]
      }
    ],
    "outputs": [],
    "stateMutability": "nonpayable"
  },
  {
    "type": "function",
    "name": "claimBudget",
    "inputs": [],
    "outputs": [
      {
        "name": "",
        "type": "uint256"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "claimVerifier",
    "inputs": [],
    "outputs": [
      {
        "name": "",
        "type": "address"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "cur",
    "inputs": [
      {
        "name": "coin",
        "type": "address"
      },
      {
        "name": "",
        "type": "uint256"
      }
    ],
    "outputs": [
      {
        "name": "",
        "type": "uint32"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "epochKey",
    "inputs": [
      {
        "name": "coin",
        "type": "address"
      },
      {
        "name": "seq",
        "type": "uint32"
      },
      {
        "name": "dir",
        "type": "uint8"
      }
    ],
    "outputs": [
      {
        "name": "",
        "type": "uint256"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "epochOf",
    "inputs": [
      {
        "name": "coin",
        "type": "address"
      },
      {
        "name": "dir",
        "type": "uint8"
      },
      {
        "name": "seq",
        "type": "uint32"
      }
    ],
    "outputs": [
      {
        "name": "",
        "type": "tuple",
        "components": [
          {
            "name": "startedAt",
            "type": "uint64"
          },
          {
            "name": "status",
            "type": "uint8"
          },
          {
            "name": "keyId",
            "type": "uint32"
          },
          {
            "name": "count",
            "type": "uint32"
          },
          {
            "name": "refPrice",
            "type": "uint256"
          },
          {
            "name": "refVb",
            "type": "uint256"
          },
          {
            "name": "c1",
            "type": "tuple",
            "components": [
              {
                "name": "x",
                "type": "uint256"
              },
              {
                "name": "y",
                "type": "uint256"
              },
              {
                "name": "t",
                "type": "uint256"
              },
              {
                "name": "z",
                "type": "uint256"
              }
            ]
          },
          {
            "name": "c2",
            "type": "tuple",
            "components": [
              {
                "name": "x",
                "type": "uint256"
              },
              {
                "name": "y",
                "type": "uint256"
              },
              {
                "name": "t",
                "type": "uint256"
              },
              {
                "name": "z",
                "type": "uint256"
              }
            ]
          }
        ]
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "epochsOf",
    "inputs": [
      {
        "name": "coins",
        "type": "address[]"
      }
    ],
    "outputs": [
      {
        "name": "out",
        "type": "tuple[3][]",
        "components": [
          {
            "name": "startedAt",
            "type": "uint64"
          },
          {
            "name": "status",
            "type": "uint8"
          },
          {
            "name": "keyId",
            "type": "uint32"
          },
          {
            "name": "count",
            "type": "uint32"
          },
          {
            "name": "refPrice",
            "type": "uint256"
          },
          {
            "name": "refVb",
            "type": "uint256"
          },
          {
            "name": "c1",
            "type": "tuple",
            "components": [
              {
                "name": "x",
                "type": "uint256"
              },
              {
                "name": "y",
                "type": "uint256"
              },
              {
                "name": "t",
                "type": "uint256"
              },
              {
                "name": "z",
                "type": "uint256"
              }
            ]
          },
          {
            "name": "c2",
            "type": "tuple",
            "components": [
              {
                "name": "x",
                "type": "uint256"
              },
              {
                "name": "y",
                "type": "uint256"
              },
              {
                "name": "t",
                "type": "uint256"
              },
              {
                "name": "z",
                "type": "uint256"
              }
            ]
          }
        ]
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "fundClaimBudget",
    "inputs": [],
    "outputs": [],
    "stateMutability": "payable"
  },
  {
    "type": "function",
    "name": "hashClaimExt",
    "inputs": [
      {
        "name": "e",
        "type": "tuple",
        "components": [
          {
            "name": "relayer",
            "type": "address"
          },
          {
            "name": "encryptedOutputs",
            "type": "bytes[2]"
          }
        ]
      }
    ],
    "outputs": [
      {
        "name": "",
        "type": "bytes32"
      }
    ],
    "stateMutability": "pure"
  },
  {
    "type": "function",
    "name": "hashIntentExt",
    "inputs": [
      {
        "name": "e",
        "type": "tuple",
        "components": [
          {
            "name": "relayer",
            "type": "address"
          },
          {
            "name": "fee",
            "type": "uint256"
          },
          {
            "name": "encryptedOutputs",
            "type": "bytes[3]"
          }
        ]
      }
    ],
    "outputs": [
      {
        "name": "",
        "type": "bytes32"
      }
    ],
    "stateMutability": "pure"
  },
  {
    "type": "function",
    "name": "intentLeaf",
    "inputs": [
      {
        "name": "commitment",
        "type": "uint256"
      },
      {
        "name": "epochKey_",
        "type": "uint256"
      }
    ],
    "outputs": [
      {
        "name": "",
        "type": "uint256"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "intentVerifier",
    "inputs": [],
    "outputs": [
      {
        "name": "",
        "type": "address"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "isOpenable",
    "inputs": [
      {
        "name": "coin",
        "type": "address"
      },
      {
        "name": "dir",
        "type": "uint8"
      },
      {
        "name": "seq",
        "type": "uint32"
      }
    ],
    "outputs": [
      {
        "name": "",
        "type": "bool"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "isVoidable",
    "inputs": [
      {
        "name": "coin",
        "type": "address"
      },
      {
        "name": "dir",
        "type": "uint8"
      },
      {
        "name": "seq",
        "type": "uint32"
      }
    ],
    "outputs": [
      {
        "name": "",
        "type": "bool"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "keyByGen",
    "inputs": [
      {
        "name": "gen",
        "type": "uint256"
      },
      {
        "name": "",
        "type": "uint256"
      }
    ],
    "outputs": [
      {
        "name": "",
        "type": "uint256"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "keyGen",
    "inputs": [],
    "outputs": [
      {
        "name": "",
        "type": "uint32"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "keySwitchAt",
    "inputs": [],
    "outputs": [
      {
        "name": "",
        "type": "uint64"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "launchpad",
    "inputs": [],
    "outputs": [
      {
        "name": "",
        "type": "address"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "maxReimburseGasPrice",
    "inputs": [],
    "outputs": [
      {
        "name": "",
        "type": "uint256"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "openEpoch",
    "inputs": [
      {
        "name": "coin",
        "type": "address"
      },
      {
        "name": "dirMask",
        "type": "uint8"
      },
      {
        "name": "seq",
        "type": "uint32[3]"
      },
      {
        "name": "u",
        "type": "uint256[3]"
      },
      {
        "name": "proofs",
        "type": "tuple[3]",
        "components": [
          {
            "name": "a",
            "type": "uint256[2]"
          },
          {
            "name": "b",
            "type": "uint256[2][2]"
          },
          {
            "name": "c",
            "type": "uint256[2]"
          }
        ]
      },
      {
        "name": "minOut",
        "type": "uint256[3]"
      }
    ],
    "outputs": [],
    "stateMutability": "nonpayable"
  },
  {
    "type": "function",
    "name": "openVerifier",
    "inputs": [],
    "outputs": [
      {
        "name": "",
        "type": "address"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "owner",
    "inputs": [],
    "outputs": [
      {
        "name": "",
        "type": "address"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "params",
    "inputs": [],
    "outputs": [
      {
        "name": "tMin",
        "type": "uint32"
      },
      {
        "name": "tMax",
        "type": "uint32"
      },
      {
        "name": "k",
        "type": "uint32"
      },
      {
        "name": "grace",
        "type": "uint32"
      },
      {
        "name": "bandBps",
        "type": "uint16"
      },
      {
        "name": "maxIntents",
        "type": "uint16"
      },
      {
        "name": "bandFloorWei",
        "type": "uint128"
      },
      {
        "name": "claimGas",
        "type": "uint32"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "pendingOwner",
    "inputs": [],
    "outputs": [
      {
        "name": "",
        "type": "address"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "pool",
    "inputs": [],
    "outputs": [
      {
        "name": "",
        "type": "address"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "renounceOwnership",
    "inputs": [],
    "outputs": [],
    "stateMutability": "nonpayable"
  },
  {
    "type": "function",
    "name": "resultLeaf",
    "inputs": [
      {
        "name": "epochKey_",
        "type": "uint256"
      },
      {
        "name": "totalIn",
        "type": "uint256"
      },
      {
        "name": "totalOut",
        "type": "uint256"
      },
      {
        "name": "totalRefund",
        "type": "uint256"
      },
      {
        "name": "rptAtSettle",
        "type": "uint256"
      }
    ],
    "outputs": [
      {
        "name": "",
        "type": "uint256"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "roots",
    "inputs": [],
    "outputs": [
      {
        "name": "",
        "type": "address"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "router",
    "inputs": [],
    "outputs": [
      {
        "name": "",
        "type": "address"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "seenC1",
    "inputs": [
      {
        "name": "c1x",
        "type": "uint256"
      }
    ],
    "outputs": [
      {
        "name": "",
        "type": "bool"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "setCoordinatorKey",
    "inputs": [
      {
        "name": "pk",
        "type": "uint256[2]"
      },
      {
        "name": "switchAt",
        "type": "uint64"
      }
    ],
    "outputs": [],
    "stateMutability": "nonpayable"
  },
  {
    "type": "function",
    "name": "setMaxReimburseGasPrice",
    "inputs": [
      {
        "name": "wei_",
        "type": "uint256"
      }
    ],
    "outputs": [],
    "stateMutability": "nonpayable"
  },
  {
    "type": "function",
    "name": "setParams",
    "inputs": [
      {
        "name": "p",
        "type": "tuple",
        "components": [
          {
            "name": "tMin",
            "type": "uint32"
          },
          {
            "name": "tMax",
            "type": "uint32"
          },
          {
            "name": "k",
            "type": "uint32"
          },
          {
            "name": "grace",
            "type": "uint32"
          },
          {
            "name": "bandBps",
            "type": "uint16"
          },
          {
            "name": "maxIntents",
            "type": "uint16"
          },
          {
            "name": "bandFloorWei",
            "type": "uint128"
          },
          {
            "name": "claimGas",
            "type": "uint32"
          }
        ]
      }
    ],
    "outputs": [],
    "stateMutability": "nonpayable"
  },
  {
    "type": "function",
    "name": "spot",
    "inputs": [
      {
        "name": "coin",
        "type": "address"
      }
    ],
    "outputs": [
      {
        "name": "price",
        "type": "uint256"
      },
      {
        "name": "vB",
        "type": "uint256"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "submitIntent",
    "inputs": [
      {
        "name": "p",
        "type": "tuple",
        "components": [
          {
            "name": "a",
            "type": "uint256[2]"
          },
          {
            "name": "b",
            "type": "uint256[2][2]"
          },
          {
            "name": "c",
            "type": "uint256[2]"
          }
        ]
      },
      {
        "name": "s",
        "type": "tuple",
        "components": [
          {
            "name": "root",
            "type": "uint256"
          },
          {
            "name": "publicAmount",
            "type": "uint256"
          },
          {
            "name": "coin",
            "type": "address"
          },
          {
            "name": "accRpt",
            "type": "uint256"
          },
          {
            "name": "dir",
            "type": "uint8"
          },
          {
            "name": "ecPk",
            "type": "uint256[2]"
          },
          {
            "name": "c1",
            "type": "uint256[2]"
          },
          {
            "name": "c2",
            "type": "uint256[2]"
          },
          {
            "name": "extDataHash",
            "type": "bytes32"
          },
          {
            "name": "inputNullifiers",
            "type": "uint256[2]"
          },
          {
            "name": "outputCommitments",
            "type": "uint256[3]"
          }
        ]
      },
      {
        "name": "e",
        "type": "tuple",
        "components": [
          {
            "name": "relayer",
            "type": "address"
          },
          {
            "name": "fee",
            "type": "uint256"
          },
          {
            "name": "encryptedOutputs",
            "type": "bytes[3]"
          }
        ]
      }
    ],
    "outputs": [],
    "stateMutability": "nonpayable"
  },
  {
    "type": "function",
    "name": "transferOwnership",
    "inputs": [
      {
        "name": "newOwner",
        "type": "address"
      }
    ],
    "outputs": [],
    "stateMutability": "nonpayable"
  },
  {
    "type": "function",
    "name": "treasury",
    "inputs": [],
    "outputs": [
      {
        "name": "",
        "type": "address"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "verifyClaim",
    "inputs": [
      {
        "name": "p",
        "type": "tuple",
        "components": [
          {
            "name": "a",
            "type": "uint256[2]"
          },
          {
            "name": "b",
            "type": "uint256[2][2]"
          },
          {
            "name": "c",
            "type": "uint256[2]"
          }
        ]
      },
      {
        "name": "s",
        "type": "tuple",
        "components": [
          {
            "name": "root",
            "type": "uint256"
          },
          {
            "name": "nullifier",
            "type": "uint256"
          },
          {
            "name": "outputCommitments",
            "type": "uint256[2]"
          },
          {
            "name": "extDataHash",
            "type": "bytes32"
          }
        ]
      }
    ],
    "outputs": [
      {
        "name": "",
        "type": "bool"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "verifyIntent",
    "inputs": [
      {
        "name": "p",
        "type": "tuple",
        "components": [
          {
            "name": "a",
            "type": "uint256[2]"
          },
          {
            "name": "b",
            "type": "uint256[2][2]"
          },
          {
            "name": "c",
            "type": "uint256[2]"
          }
        ]
      },
      {
        "name": "s",
        "type": "tuple",
        "components": [
          {
            "name": "root",
            "type": "uint256"
          },
          {
            "name": "publicAmount",
            "type": "uint256"
          },
          {
            "name": "coin",
            "type": "address"
          },
          {
            "name": "accRpt",
            "type": "uint256"
          },
          {
            "name": "dir",
            "type": "uint8"
          },
          {
            "name": "ecPk",
            "type": "uint256[2]"
          },
          {
            "name": "c1",
            "type": "uint256[2]"
          },
          {
            "name": "c2",
            "type": "uint256[2]"
          },
          {
            "name": "extDataHash",
            "type": "bytes32"
          },
          {
            "name": "inputNullifiers",
            "type": "uint256[2]"
          },
          {
            "name": "outputCommitments",
            "type": "uint256[3]"
          }
        ]
      }
    ],
    "outputs": [
      {
        "name": "",
        "type": "bool"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "verifyOpen",
    "inputs": [
      {
        "name": "p",
        "type": "tuple",
        "components": [
          {
            "name": "a",
            "type": "uint256[2]"
          },
          {
            "name": "b",
            "type": "uint256[2][2]"
          },
          {
            "name": "c",
            "type": "uint256[2]"
          }
        ]
      },
      {
        "name": "ecPk",
        "type": "uint256[2]"
      },
      {
        "name": "c1",
        "type": "uint256[2]"
      },
      {
        "name": "c2",
        "type": "uint256[2]"
      },
      {
        "name": "u",
        "type": "uint256"
      }
    ],
    "outputs": [
      {
        "name": "",
        "type": "bool"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "voidEpoch",
    "inputs": [
      {
        "name": "coin",
        "type": "address"
      },
      {
        "name": "dir",
        "type": "uint8"
      },
      {
        "name": "seq",
        "type": "uint32"
      }
    ],
    "outputs": [],
    "stateMutability": "nonpayable"
  },
  {
    "type": "function",
    "name": "weth",
    "inputs": [],
    "outputs": [
      {
        "name": "",
        "type": "address"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "event",
    "name": "ClaimBudgetFunded",
    "inputs": [
      {
        "name": "amount",
        "type": "uint256",
        "indexed": false
      }
    ],
    "anonymous": false
  },
  {
    "type": "event",
    "name": "Claimed",
    "inputs": [
      {
        "name": "relayer",
        "type": "address",
        "indexed": false
      },
      {
        "name": "reimbursed",
        "type": "uint256",
        "indexed": false
      }
    ],
    "anonymous": false
  },
  {
    "type": "event",
    "name": "CoordinatorKeySet",
    "inputs": [
      {
        "name": "pk",
        "type": "uint256[2]",
        "indexed": false
      },
      {
        "name": "switchAt",
        "type": "uint64",
        "indexed": false
      }
    ],
    "anonymous": false
  },
  {
    "type": "event",
    "name": "EpochOpened",
    "inputs": [
      {
        "name": "coin",
        "type": "address",
        "indexed": true
      },
      {
        "name": "dir",
        "type": "uint8",
        "indexed": true
      },
      {
        "name": "seq",
        "type": "uint32",
        "indexed": false
      },
      {
        "name": "u",
        "type": "uint256",
        "indexed": false
      },
      {
        "name": "totalIn",
        "type": "uint256",
        "indexed": false
      },
      {
        "name": "totalOut",
        "type": "uint256",
        "indexed": false
      },
      {
        "name": "refund",
        "type": "uint256",
        "indexed": false
      },
      {
        "name": "spotAfter",
        "type": "uint256",
        "indexed": false
      },
      {
        "name": "rptAtSettle",
        "type": "uint256",
        "indexed": false
      }
    ],
    "anonymous": false
  },
  {
    "type": "event",
    "name": "EpochVoided",
    "inputs": [
      {
        "name": "coin",
        "type": "address",
        "indexed": true
      },
      {
        "name": "dir",
        "type": "uint8",
        "indexed": true
      },
      {
        "name": "seq",
        "type": "uint32",
        "indexed": false
      }
    ],
    "anonymous": false
  },
  {
    "type": "event",
    "name": "IntentSubmitted",
    "inputs": [
      {
        "name": "coin",
        "type": "address",
        "indexed": true
      },
      {
        "name": "dir",
        "type": "uint8",
        "indexed": true
      },
      {
        "name": "seq",
        "type": "uint32",
        "indexed": false
      },
      {
        "name": "count",
        "type": "uint32",
        "indexed": false
      },
      {
        "name": "intentLeaf",
        "type": "uint256",
        "indexed": false
      }
    ],
    "anonymous": false
  },
  {
    "type": "event",
    "name": "MaxReimburseGasPriceSet",
    "inputs": [
      {
        "name": "wei_",
        "type": "uint256",
        "indexed": false
      }
    ],
    "anonymous": false
  },
  {
    "type": "event",
    "name": "OwnershipTransferStarted",
    "inputs": [
      {
        "name": "previousOwner",
        "type": "address",
        "indexed": true
      },
      {
        "name": "newOwner",
        "type": "address",
        "indexed": true
      }
    ],
    "anonymous": false
  },
  {
    "type": "event",
    "name": "OwnershipTransferred",
    "inputs": [
      {
        "name": "previousOwner",
        "type": "address",
        "indexed": true
      },
      {
        "name": "newOwner",
        "type": "address",
        "indexed": true
      }
    ],
    "anonymous": false
  },
  {
    "type": "event",
    "name": "ParamsSet",
    "inputs": [
      {
        "name": "p",
        "type": "tuple",
        "indexed": false,
        "components": [
          {
            "name": "tMin",
            "type": "uint32"
          },
          {
            "name": "tMax",
            "type": "uint32"
          },
          {
            "name": "k",
            "type": "uint32"
          },
          {
            "name": "grace",
            "type": "uint32"
          },
          {
            "name": "bandBps",
            "type": "uint16"
          },
          {
            "name": "maxIntents",
            "type": "uint16"
          },
          {
            "name": "bandFloorWei",
            "type": "uint128"
          },
          {
            "name": "claimGas",
            "type": "uint32"
          }
        ]
      }
    ],
    "anonymous": false
  },
  {
    "type": "error",
    "name": "AlreadySpent",
    "inputs": []
  },
  {
    "type": "error",
    "name": "BadDir",
    "inputs": []
  },
  {
    "type": "error",
    "name": "BadExtDataHash",
    "inputs": []
  },
  {
    "type": "error",
    "name": "BadPublicAmount",
    "inputs": []
  },
  {
    "type": "error",
    "name": "BadValue",
    "inputs": []
  },
  {
    "type": "error",
    "name": "BandExceeded",
    "inputs": [
      {
        "name": "dir",
        "type": "uint8"
      }
    ]
  },
  {
    "type": "error",
    "name": "EmptyMask",
    "inputs": []
  },
  {
    "type": "error",
    "name": "EpochFull",
    "inputs": []
  },
  {
    "type": "error",
    "name": "FeeTooHigh",
    "inputs": []
  },
  {
    "type": "error",
    "name": "InvalidProof",
    "inputs": []
  },
  {
    "type": "error",
    "name": "NotCoin",
    "inputs": []
  },
  {
    "type": "error",
    "name": "NotOnCurve",
    "inputs": []
  },
  {
    "type": "error",
    "name": "NotOpenable",
    "inputs": [
      {
        "name": "dir",
        "type": "uint8"
      }
    ]
  },
  {
    "type": "error",
    "name": "NotVoidable",
    "inputs": []
  },
  {
    "type": "error",
    "name": "OutOfBounds",
    "inputs": []
  },
  {
    "type": "error",
    "name": "OwnableInvalidOwner",
    "inputs": [
      {
        "name": "owner",
        "type": "address"
      }
    ]
  },
  {
    "type": "error",
    "name": "OwnableUnauthorizedAccount",
    "inputs": [
      {
        "name": "account",
        "type": "address"
      }
    ]
  },
  {
    "type": "error",
    "name": "PendingKey",
    "inputs": []
  },
  {
    "type": "error",
    "name": "ReentrancyGuardReentrantCall",
    "inputs": []
  },
  {
    "type": "error",
    "name": "ReusedRandomness",
    "inputs": []
  },
  {
    "type": "error",
    "name": "SafeERC20FailedOperation",
    "inputs": [
      {
        "name": "token",
        "type": "address"
      }
    ]
  },
  {
    "type": "error",
    "name": "TransferFailed",
    "inputs": []
  },
  {
    "type": "error",
    "name": "UnknownAccRpt",
    "inputs": []
  },
  {
    "type": "error",
    "name": "UnknownRoot",
    "inputs": []
  },
  {
    "type": "error",
    "name": "WrongKey",
    "inputs": []
  },
  {
    "type": "error",
    "name": "WrongSeq",
    "inputs": [
      {
        "name": "dir",
        "type": "uint8"
      }
    ]
  }
] as const;

export const planterAbi = [
  {
    "type": "constructor",
    "inputs": [
      {
        "name": "pool_",
        "type": "address"
      },
      {
        "name": "launchpad_",
        "type": "address"
      },
      {
        "name": "feeRouter_",
        "type": "address"
      },
      {
        "name": "roots_",
        "type": "address"
      }
    ],
    "stateMutability": "nonpayable"
  },
  {
    "type": "receive",
    "stateMutability": "payable"
  },
  {
    "type": "function",
    "name": "feeRouter",
    "inputs": [],
    "outputs": [
      {
        "name": "",
        "type": "address"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "handOver",
    "inputs": [
      {
        "name": "coin",
        "type": "address"
      },
      {
        "name": "handle",
        "type": "uint256"
      },
      {
        "name": "mode",
        "type": "uint8"
      },
      {
        "name": "wallet",
        "type": "address"
      },
      {
        "name": "ringId",
        "type": "uint256"
      }
    ],
    "outputs": [],
    "stateMutability": "nonpayable"
  },
  {
    "type": "function",
    "name": "harvestToHandle",
    "inputs": [
      {
        "name": "coin",
        "type": "address"
      },
      {
        "name": "tokens",
        "type": "uint256"
      },
      {
        "name": "minBnb",
        "type": "uint256"
      },
      {
        "name": "handle",
        "type": "uint256"
      }
    ],
    "outputs": [],
    "stateMutability": "nonpayable"
  },
  {
    "type": "function",
    "name": "launchpad",
    "inputs": [],
    "outputs": [
      {
        "name": "",
        "type": "address"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "plantFor",
    "inputs": [
      {
        "name": "payload",
        "type": "bytes"
      }
    ],
    "outputs": [
      {
        "name": "coin",
        "type": "address"
      }
    ],
    "stateMutability": "payable"
  },
  {
    "type": "function",
    "name": "pool",
    "inputs": [],
    "outputs": [
      {
        "name": "",
        "type": "address"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "predictStub",
    "inputs": [
      {
        "name": "handle",
        "type": "uint256"
      },
      {
        "name": "nonce",
        "type": "uint256"
      }
    ],
    "outputs": [
      {
        "name": "",
        "type": "address"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "roots",
    "inputs": [],
    "outputs": [
      {
        "name": "",
        "type": "address"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "stubNonce",
    "inputs": [],
    "outputs": [
      {
        "name": "",
        "type": "uint256"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "stubOf",
    "inputs": [
      {
        "name": "coin",
        "type": "address"
      }
    ],
    "outputs": [
      {
        "name": "",
        "type": "address"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "event",
    "name": "HandedOverPrivately",
    "inputs": [
      {
        "name": "coin",
        "type": "address",
        "indexed": true
      },
      {
        "name": "mode",
        "type": "uint8",
        "indexed": false
      },
      {
        "name": "wallet",
        "type": "address",
        "indexed": false
      },
      {
        "name": "ringId",
        "type": "uint256",
        "indexed": false
      }
    ],
    "anonymous": false
  },
  {
    "type": "event",
    "name": "HarvestedToHandle",
    "inputs": [
      {
        "name": "coin",
        "type": "address",
        "indexed": true
      },
      {
        "name": "tokens",
        "type": "uint256",
        "indexed": false
      },
      {
        "name": "bnb",
        "type": "uint256",
        "indexed": false
      },
      {
        "name": "handle",
        "type": "uint256",
        "indexed": false
      }
    ],
    "anonymous": false
  },
  {
    "type": "event",
    "name": "PlantedPrivately",
    "inputs": [
      {
        "name": "coin",
        "type": "address",
        "indexed": true
      },
      {
        "name": "stub",
        "type": "address",
        "indexed": false
      },
      {
        "name": "handle",
        "type": "uint256",
        "indexed": false
      }
    ],
    "anonymous": false
  },
  {
    "type": "error",
    "name": "BadHandle",
    "inputs": []
  },
  {
    "type": "error",
    "name": "BadPayload",
    "inputs": []
  },
  {
    "type": "error",
    "name": "BadPlantValue",
    "inputs": []
  },
  {
    "type": "error",
    "name": "NotPool",
    "inputs": []
  },
  {
    "type": "error",
    "name": "ReentrancyGuardReentrantCall",
    "inputs": []
  },
  {
    "type": "error",
    "name": "SafeERC20FailedOperation",
    "inputs": [
      {
        "name": "token",
        "type": "address"
      }
    ]
  },
  {
    "type": "error",
    "name": "UnknownCoin",
    "inputs": []
  },
  {
    "type": "error",
    "name": "WalletModeRefused",
    "inputs": []
  },
  {
    "type": "error",
    "name": "WrongHandle",
    "inputs": []
  }
] as const;

export const creatorStubAbi = [
  {
    "type": "constructor",
    "inputs": [
      {
        "name": "planter_",
        "type": "address"
      },
      {
        "name": "pool_",
        "type": "address"
      },
      {
        "name": "launchpad_",
        "type": "address"
      },
      {
        "name": "feeRouter_",
        "type": "address"
      },
      {
        "name": "handle_",
        "type": "uint256"
      }
    ],
    "stateMutability": "nonpayable"
  },
  {
    "type": "receive",
    "stateMutability": "payable"
  },
  {
    "type": "function",
    "name": "coin",
    "inputs": [],
    "outputs": [
      {
        "name": "",
        "type": "address"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "feeRouter",
    "inputs": [],
    "outputs": [
      {
        "name": "",
        "type": "address"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "flush",
    "inputs": [],
    "outputs": [],
    "stateMutability": "nonpayable"
  },
  {
    "type": "function",
    "name": "handOver",
    "inputs": [
      {
        "name": "mode",
        "type": "uint8"
      },
      {
        "name": "wallet",
        "type": "address"
      },
      {
        "name": "ringId",
        "type": "uint256"
      }
    ],
    "outputs": [],
    "stateMutability": "nonpayable"
  },
  {
    "type": "function",
    "name": "handle",
    "inputs": [],
    "outputs": [
      {
        "name": "",
        "type": "uint256"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "launchpad",
    "inputs": [],
    "outputs": [
      {
        "name": "",
        "type": "address"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "plant",
    "inputs": [
      {
        "name": "p",
        "type": "tuple",
        "components": [
          {
            "name": "name",
            "type": "string"
          },
          {
            "name": "symbol",
            "type": "string"
          },
          {
            "name": "metadata",
            "type": "tuple",
            "components": [
              {
                "name": "description",
                "type": "string"
              },
              {
                "name": "image",
                "type": "string"
              },
              {
                "name": "website",
                "type": "string"
              },
              {
                "name": "twitter",
                "type": "string"
              },
              {
                "name": "telegram",
                "type": "string"
              }
            ]
          },
          {
            "name": "payoutMode",
            "type": "uint8"
          },
          {
            "name": "payoutWallet",
            "type": "address"
          },
          {
            "name": "ringId",
            "type": "uint256"
          },
          {
            "name": "minFirstBuyTokens",
            "type": "uint256"
          }
        ]
      }
    ],
    "outputs": [
      {
        "name": "c",
        "type": "address"
      }
    ],
    "stateMutability": "payable"
  },
  {
    "type": "function",
    "name": "planter",
    "inputs": [],
    "outputs": [
      {
        "name": "",
        "type": "address"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "pool",
    "inputs": [],
    "outputs": [
      {
        "name": "",
        "type": "address"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "event",
    "name": "Flushed",
    "inputs": [
      {
        "name": "amount",
        "type": "uint256",
        "indexed": false
      }
    ],
    "anonymous": false
  },
  {
    "type": "error",
    "name": "AlreadyPlanted",
    "inputs": []
  },
  {
    "type": "error",
    "name": "NotPlanted",
    "inputs": []
  },
  {
    "type": "error",
    "name": "NotPlanter",
    "inputs": []
  }
] as const;
