/**
 * Baby Jubjub (circomlib) arithmetic for the stage-2 Epoch Coordinator — privacy/PRIVACY-SPEC.md §2.7.
 *
 * Twisted Edwards a·x² + y² = 1 + d·x²·y² over the BN254 scalar field, a = 168700, d = 168696, generator Base8 of
 * the prime-order subgroup (order l = SUBORDER). Mirrors circuits/lib/grove-zk-v2.mjs and
 * contracts/src/libraries/BabyJubjub.sol: affine points are [x, y]; extended coordinates (X, Y, T, Z) with
 * x = X/Z, y = Y/Z, T = X·Y/Z are used for chains of additions (no inversion per add).
 */

export const FIELD_SIZE = 21888242871839275222246405745257275088548364400416034343698204186575808495617n;
const P = FIELD_SIZE;

export const A = 168700n;
export const D = 168696n;
/** Full curve order (8 · SUBORDER). */
export const ORDER = 21888242871839275222246405745257275088614511777268538073601725287587578984328n;
/** l: order of the subgroup generated by BASE8. Scalars (ecSk, k) live in [1, l). */
export const SUBORDER = 2736030358979909402780800718157159386076813972158567259200215660948447373041n;

export type Point = readonly [bigint, bigint];

export const BASE8: Point = Object.freeze([
  5299619240641551281634865583518297030282874472190772894086521144482721001553n,
  16950150798460657717958625567821834550301663161624707787222815936182638968203n,
]) as Point;

export const IDENTITY: Point = Object.freeze([0n, 1n]) as Point;

/** Extended coordinates. */
export interface Ext {
  X: bigint;
  Y: bigint;
  T: bigint;
  Z: bigint;
}

export const EXT_IDENTITY: Readonly<Ext> = Object.freeze({ X: 0n, Y: 1n, T: 0n, Z: 1n });

/** The contract's Point struct (BabyJubjub.sol), lower-case field names. */
export interface ContractPoint {
  x: bigint;
  y: bigint;
  t: bigint;
  z: bigint;
}

export function mod(a: bigint): bigint {
  const r = a % P;
  return r < 0n ? r + P : r;
}

export function modInv(a: bigint): bigint {
  let t = 0n;
  let newT = 1n;
  let r = P;
  let newR = mod(a);
  if (newR === 0n) throw new Error("inverse of zero");
  while (newR !== 0n) {
    const q = r / newR;
    [t, newT] = [newT, t - q * newT];
    [r, newR] = [newR, r - q * newR];
  }
  return mod(t);
}

/** Montgomery's trick: inverses of many non-zero field elements with one inversion. */
export function batchInverse(xs: readonly bigint[]): bigint[] {
  const n = xs.length;
  const out = new Array<bigint>(n);
  if (n === 0) return out;
  const prefix = new Array<bigint>(n);
  let acc = 1n;
  for (let i = 0; i < n; i++) {
    prefix[i] = acc;
    acc = (acc * xs[i]) % P;
  }
  let inv = modInv(acc);
  for (let i = n - 1; i >= 0; i--) {
    out[i] = (inv * prefix[i]) % P;
    inv = (inv * xs[i]) % P;
  }
  return out;
}

export function toExt(p: Point): Ext {
  const x = mod(BigInt(p[0]));
  const y = mod(BigInt(p[1]));
  return { X: x, Y: y, T: (x * y) % P, Z: 1n };
}

export function extToAffine(e: Ext): Point {
  const zi = modInv(e.Z);
  return [(e.X * zi) % P, (e.Y * zi) % P];
}

/** add-2008-hwcd for twisted Edwards with a ≠ −1 (complete on this curve: d is a non-square). */
export function extAdd(p: Ext, q: Ext): Ext {
  const a = (p.X * q.X) % P;
  const b = (p.Y * q.Y) % P;
  const c = (((D * p.T) % P) * q.T) % P;
  const d = (p.Z * q.Z) % P;
  const e = mod((p.X + p.Y) * (q.X + q.Y) - a - b);
  const f = mod(d - c);
  const g = (d + c) % P;
  const h = mod(b - A * a);
  return { X: (e * f) % P, Y: (g * h) % P, T: (e * h) % P, Z: (f * g) % P };
}

export function extNeg(p: Ext): Ext {
  return { X: mod(-p.X), Y: p.Y, T: mod(-p.T), Z: p.Z };
}

/** Double-and-add; k ≥ 0. */
export function extMul(k: bigint, p: Ext): Ext {
  let n = BigInt(k);
  if (n < 0n) throw new Error("negative scalar");
  let r: Ext = EXT_IDENTITY;
  let base = p;
  while (n > 0n) {
    if (n & 1n) r = extAdd(r, base);
    base = extAdd(base, base);
    n >>= 1n;
  }
  return r;
}

/** Projective equality: X1·Z2 == X2·Z1 and Y1·Z2 == Y2·Z1. */
export function extEq(p: Ext, q: Ext): boolean {
  return (p.X * q.Z) % P === (q.X * p.Z) % P && (p.Y * q.Z) % P === (q.Y * p.Z) % P;
}

export function add(p: Point, q: Point): Point {
  return extToAffine(extAdd(toExt(p), toExt(q)));
}

export function neg(p: Point): Point {
  return [mod(-BigInt(p[0])), mod(BigInt(p[1]))];
}

export function mul(k: bigint, p: Point): Point {
  return extToAffine(extMul(k, toExt(p)));
}

export function eq(p: Point, q: Point): boolean {
  return mod(BigInt(p[0])) === mod(BigInt(q[0])) && mod(BigInt(p[1])) === mod(BigInt(q[1]));
}

export function isOnCurve(p: Point): boolean {
  const x = mod(BigInt(p[0]));
  const y = mod(BigInt(p[1]));
  const x2 = (x * x) % P;
  const y2 = (y * y) % P;
  return mod(A * x2 + y2) === mod(1n + (((D * x2) % P) * y2) % P);
}

/** On the curve and l·p = identity (the check the contract applies to a new coordinator key). */
export function inSubgroup(p: Point): boolean {
  return isOnCurve(p) && extEq(extMul(SUBORDER, toExt(p)), EXT_IDENTITY);
}

/** Affine → the contract's extended Point (Z = 1). */
export function toContractPoint(p: Point): ContractPoint {
  const e = toExt(p);
  return { x: e.X, y: e.Y, t: e.T, z: e.Z };
}

/** The contract's extended Point → affine (what `BabyJubjub.toAffine` returns). */
export function fromContractPoint(e: { x: bigint | string; y: bigint | string; t: bigint | string; z: bigint | string }): Point {
  return extToAffine({ X: mod(BigInt(e.x)), Y: mod(BigInt(e.y)), T: mod(BigInt(e.t)), Z: mod(BigInt(e.z)) });
}
