// SPDX-License-Identifier: MIT
pragma solidity ^0.8.26;

import {Test, console2} from "forge-std/Test.sol";
import {stdJson} from "forge-std/StdJson.sol";
import {ShieldedPool} from "../src/ShieldedPool.sol";
import {Groth16Verifier} from "../src/Groth16Verifier.sol";
import {IPoseidonT3, IPoseidonT4} from "../src/interfaces/IGrove.sol";

/// Fixture: contracts/test/fixtures/pool.json, generated by `cd circuits && npm run fixtures`.
contract ShieldedPoolTest is Test {
    using stdJson for string;

    address constant RECIPIENT = 0x1111111111111111111111111111111111111111;
    address constant RELAYER = 0x2222222222222222222222222222222222222222;

    address poseidonT3;
    address poseidonT4;
    Groth16Verifier verifier;
    ShieldedPool pool;
    string json;

    function setUp() public {
        poseidonT3 = deployBytecode("poseidon/PoseidonT3.bin");
        poseidonT4 = deployBytecode("poseidon/PoseidonT4.bin");
        verifier = new Groth16Verifier();
        pool = new ShieldedPool(address(verifier), poseidonT3, poseidonT4, address(this));
        json = vm.readFile("test/fixtures/pool.json");
        vm.deal(address(this), 1000 ether);
    }

    // ------------------------------------------------------------ helpers

    function deployBytecode(string memory path) internal returns (address addr) {
        bytes memory code = vm.parseBytes(string.concat("0x", vm.readFile(path)));
        assembly {
            addr := create(0, add(code, 0x20), mload(code))
        }
        require(addr != address(0), "deploy failed");
    }

    function loadProof(string memory key) internal view returns (ShieldedPool.Proof memory p) {
        uint256[] memory a = json.readUintArray(string.concat(key, ".proof.a"));
        uint256[] memory b0 = json.readUintArray(string.concat(key, ".proof.b[0]"));
        uint256[] memory b1 = json.readUintArray(string.concat(key, ".proof.b[1]"));
        uint256[] memory c = json.readUintArray(string.concat(key, ".proof.c"));
        uint256[] memory n = json.readUintArray(string.concat(key, ".proof.inputNullifiers"));
        uint256[] memory o = json.readUintArray(string.concat(key, ".proof.outputCommitments"));
        p.a = [a[0], a[1]];
        p.b = [[b0[0], b0[1]], [b1[0], b1[1]]];
        p.c = [c[0], c[1]];
        p.root = json.readUint(string.concat(key, ".proof.root"));
        p.publicAmount = json.readUint(string.concat(key, ".proof.publicAmount"));
        p.extDataHash = json.readBytes32(string.concat(key, ".proof.extDataHash"));
        p.inputNullifiers = [n[0], n[1]];
        p.outputCommitments = [o[0], o[1]];
    }

    function loadExtData(string memory key) internal view returns (ShieldedPool.ExtData memory e) {
        e.recipient = json.readAddress(string.concat(key, ".extData.recipient"));
        e.extAmount = json.readInt(string.concat(key, ".extData.extAmount"));
        e.relayer = json.readAddress(string.concat(key, ".extData.relayer"));
        e.fee = json.readUint(string.concat(key, ".extData.fee"));
        e.encryptedOutput1 = json.readBytes(string.concat(key, ".extData.encryptedOutput1"));
        e.encryptedOutput2 = json.readBytes(string.concat(key, ".extData.encryptedOutput2"));
    }

    function stepValue(string memory key) internal view returns (uint256) {
        return json.readUint(string.concat(key, ".value"));
    }

    function stepRoot(string memory key) internal view returns (uint256) {
        return json.readUint(string.concat(key, ".rootAfter"));
    }

    /// Runs a fixture step through `transact` and returns the gas it used.
    function runStep(string memory key) internal returns (uint256 gasUsed) {
        ShieldedPool.Proof memory p = loadProof(key);
        ShieldedPool.ExtData memory e = loadExtData(key);
        uint256 value = stepValue(key);
        uint256 before = gasleft();
        pool.transact{value: value}(p, e);
        gasUsed = before - gasleft();
        assertEq(pool.getLastRoot(), stepRoot(key), string.concat(key, ": root after"));
    }

    // ------------------------------------------------------------ hashing / tree

    function test_hashLeftRight_matchesJs() public view {
        assertEq(pool.hashLeftRight(1, 2), json.readUint(".hashLeftRight_1_2"));
        assertEq(IPoseidonT3(poseidonT3).poseidon([uint256(1), 2]), json.readUint(".hashLeftRight_1_2"));
        assertEq(IPoseidonT4(poseidonT4).poseidon([uint256(1), 2, 3]), json.readUint(".poseidon3_1_2_3"));
    }

    function test_emptyRoot_matchesJs() public view {
        assertEq(pool.ZERO_VALUE(), json.readUint(".zeroLeaf"));
        assertEq(pool.FIELD_SIZE(), json.readUint(".fieldSize"));
        assertEq(pool.getLastRoot(), json.readUint(".emptyRoot"));
        assertTrue(pool.isKnownRoot(json.readUint(".emptyRoot")));
        assertEq(pool.nextIndex(), 0);
    }

    function test_hashExtData_matchesJs() public view {
        ShieldedPool.ExtData memory e = loadExtData(".withdraw");
        assertEq(pool.hashExtData(e), loadProof(".withdraw").extDataHash);
        assertEq(pool.calculatePublicAmount(e.extAmount, e.fee), loadProof(".withdraw").publicAmount);
    }

    // ------------------------------------------------------------ happy path

    function test_sequence_deposit_transfer_withdraw_depositFor() public {
        uint256 gasDeposit = runStep(".deposit");
        assertEq(address(pool).balance, 1 ether);
        assertEq(pool.nextIndex(), 2);

        uint256 gasTransfer = runStep(".transfer");
        assertEq(address(pool).balance, 1 ether);
        assertEq(pool.nextIndex(), 4);
        assertTrue(pool.isSpent(loadProof(".transfer").inputNullifiers[0]));

        uint256 gasWithdraw = runStep(".withdraw");
        assertEq(RECIPIENT.balance, json.readUint(".withdraw.recipientGets"));
        assertEq(RELAYER.balance, json.readUint(".withdraw.relayerGets"));
        assertEq(RECIPIENT.balance + RELAYER.balance, 0.4 ether);
        assertEq(address(pool).balance, 0.6 ether);
        assertEq(pool.nextIndex(), 6);

        // (d) depositFor: commitment computed on-chain must match the JS value
        uint256 pubKey = json.readUint(".depositFor.pubKey");
        uint256 blinding = json.readUint(".depositFor.blinding");
        uint256 amount = json.readUint(".depositFor.value");
        uint256 before = gasleft();
        uint256 index = pool.depositFor{value: amount}(pubKey, blinding);
        uint256 gasDepositFor = before - gasleft();
        assertEq(index, json.readUint(".depositFor.index"));
        assertEq(pool.getLastRoot(), stepRoot(".depositFor"));
        assertEq(IPoseidonT4(poseidonT4).poseidon([amount, pubKey, blinding]), json.readUint(".depositFor.commitment"));
        assertEq(address(pool).balance, 0.85 ether);

        uint256 recipientBefore = RECIPIENT.balance;
        uint256 gasSpend = runStep(".spendDepositFor");
        assertEq(RECIPIENT.balance - recipientBefore, amount);
        assertEq(address(pool).balance, 0.6 ether);
        assertEq(pool.nextIndex(), 9);

        console2.log("gas transact (deposit)        ", gasDeposit);
        console2.log("gas transact (private transfer)", gasTransfer);
        console2.log("gas transact (withdraw + fee)  ", gasWithdraw);
        console2.log("gas transact (spend depositFor)", gasSpend);
        console2.log("gas depositFor                 ", gasDepositFor);
    }

    function test_depositFor_emitsEvents() public {
        uint256 pubKey = json.readUint(".depositFor.pubKey");
        uint256 blinding = json.readUint(".depositFor.blinding");
        vm.expectEmit(true, false, false, true);
        emit ShieldedPool.DepositFor(pubKey, 1 ether, blinding, 0, address(this));
        pool.depositFor{value: 1 ether}(pubKey, blinding);
        assertEq(pool.nextIndex(), 1);
    }

    // ------------------------------------------------------------ rejections

    function test_revert_replayWithdraw_AlreadySpent() public {
        runStep(".deposit");
        runStep(".transfer");
        runStep(".withdraw");
        ShieldedPool.Proof memory p = loadProof(".withdraw");
        ShieldedPool.ExtData memory e = loadExtData(".withdraw");
        vm.expectRevert(ShieldedPool.AlreadySpent.selector);
        pool.transact(p, e);
    }

    function test_revert_wrongValue_BadValue() public {
        ShieldedPool.Proof memory p = loadProof(".deposit");
        ShieldedPool.ExtData memory e = loadExtData(".deposit");
        vm.expectRevert(ShieldedPool.BadValue.selector);
        pool.transact{value: 0.5 ether}(p, e);
        vm.expectRevert(ShieldedPool.BadValue.selector);
        pool.transact(p, e);
        // a non-deposit must not carry value
        runStep(".deposit");
        p = loadProof(".transfer");
        e = loadExtData(".transfer");
        vm.expectRevert(ShieldedPool.BadValue.selector);
        pool.transact{value: 1}(p, e);
    }

    function test_revert_tamperedExtData_BadExtDataHash() public {
        ShieldedPool.Proof memory p = loadProof(".deposit");
        ShieldedPool.ExtData memory e = loadExtData(".deposit");
        e.relayer = address(0xBEEF);
        vm.expectRevert(ShieldedPool.BadExtDataHash.selector);
        pool.transact{value: 1 ether}(p, e);

        e = loadExtData(".deposit");
        e.encryptedOutput1 = hex"00";
        vm.expectRevert(ShieldedPool.BadExtDataHash.selector);
        pool.transact{value: 1 ether}(p, e);
    }

    function test_revert_feeMismatch_BadPublicAmount() public {
        runStep(".deposit");
        runStep(".transfer");
        ShieldedPool.Proof memory p = loadProof(".withdraw");
        ShieldedPool.ExtData memory e = loadExtData(".withdraw");
        e.fee = e.fee + 1;
        vm.expectRevert(ShieldedPool.BadPublicAmount.selector);
        pool.transact(p, e);
    }

    function test_revert_unknownRoot_UnknownRoot() public {
        // the transfer proof is built on the root after the deposit; without it the root is unknown
        ShieldedPool.Proof memory p = loadProof(".transfer");
        ShieldedPool.ExtData memory e = loadExtData(".transfer");
        vm.expectRevert(ShieldedPool.UnknownRoot.selector);
        pool.transact(p, e);
    }

    function test_revert_tamperedProof_InvalidProof() public {
        ShieldedPool.Proof memory p = loadProof(".deposit");
        ShieldedPool.ExtData memory e = loadExtData(".deposit");
        p.c[0] = p.c[0] ^ 1;
        vm.expectRevert(ShieldedPool.InvalidProof.selector);
        pool.transact{value: 1 ether}(p, e);

        // a valid proof for different public inputs is also invalid
        p = loadProof(".deposit");
        ShieldedPool.Proof memory q = loadProof(".transfer");
        p.a = q.a;
        p.b = q.b;
        p.c = q.c;
        vm.expectRevert(ShieldedPool.InvalidProof.selector);
        pool.transact{value: 1 ether}(p, e);
    }

    /// depositFor is used by Roots / HolderRewards / DonationRotator payouts and must never be
    /// blocked by maxDeposit (only transact deposits enforce it).
    function test_depositForAboveMaxDeposit_succeeds() public {
        uint256 pubKey = json.readUint(".depositFor.pubKey");
        assertEq(pool.maxDeposit(), 100 ether);
        uint256 index = pool.depositFor{value: 101 ether}(pubKey, 1);
        assertEq(index, 0);
        assertEq(address(pool).balance, 101 ether);
        vm.expectRevert(ShieldedPool.BadValue.selector);
        pool.depositFor{value: 0}(pubKey, 1);
    }

    function test_revert_depositOverMax_OverLimit() public {
        pool.setMaxDeposit(0.5 ether);
        ShieldedPool.Proof memory p = loadProof(".deposit");
        ShieldedPool.ExtData memory e = loadExtData(".deposit");
        vm.expectRevert(ShieldedPool.OverLimit.selector);
        pool.transact{value: 1 ether}(p, e);
    }
}
