#!/usr/bin/env node
/**
 * Writes keeper/src/abis-v2.ts from the Foundry artifacts in contracts/out (privacy stage 2 contracts).
 * Run after `forge build` whenever GrovePool / DarkCurve / Planter / CreatorStub change:
 *   cd keeper && npm run sync:abis            (ABI_OUT=<dir> to read another forge --out)
 * test/abis2.test.ts fails when the generated file no longer matches the artifacts.
 */
import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

const here = path.dirname(fileURLToPath(import.meta.url));
const out = process.env.ABI_OUT ? path.resolve(process.env.ABI_OUT) : path.resolve(here, "..", "..", "contracts", "out");
const target = path.resolve(here, "..", "src", "abis-v2.ts");

export const NAMES = [
  ["GrovePool", "grovePoolAbi"],
  ["DarkCurve", "darkCurveAbi"],
  ["Planter", "planterAbi"],
  ["CreatorStub", "creatorStubAbi"],
  ["RewardPoster", "rewardPosterAbi"],
];

/** Drops compiler-only fields (internalType) so the file stays small and stable. */
export function strip(x) {
  if (Array.isArray(x)) return x.map(strip);
  if (x && typeof x === "object") {
    const o = {};
    for (const [k, v] of Object.entries(x)) {
      if (k === "internalType") continue;
      o[k] = strip(v);
    }
    return o;
  }
  return x;
}

export function loadAbi(name, dir = out) {
  const f = path.join(dir, `${name}.sol`, `${name}.json`);
  if (!fs.existsSync(f)) throw new Error(`missing ${f}: run forge build in contracts/`);
  return strip(JSON.parse(fs.readFileSync(f, "utf8")).abi);
}

export function render(dir = out) {
  const parts = [
    "// GENERATED by keeper/scripts/sync-abis.mjs from contracts/out. Do not edit by hand; rerun `npm run sync:abis`.",
    "// Privacy stage 2 (privacy/PRIVACY-SPEC.md section 4). Kept out of abis.ts so the stage-1 ABIs stay hand-written.",
    "",
  ];
  for (const [name, ident] of NAMES) {
    parts.push(`export const ${ident} = ${JSON.stringify(loadAbi(name, dir), null, 2)} as const;`, "");
  }
  return parts.join("\n");
}

if (process.argv[1] && path.resolve(process.argv[1]) === fileURLToPath(import.meta.url)) {
  const text = render();
  fs.writeFileSync(target, text);
  console.log(`wrote ${path.relative(process.cwd(), target)} (${NAMES.map((n) => n[0]).join(", ")}) from ${out}`);
}
